### ISSUE TITLE
Repo Structuur/Project

### ISSUE THREAD

**Issue by Qvdpost** [pepijnclarijs/rush-hour#1]
Er mist nog structuur in jullie project. Maak de folders aan die nodig zijn (code/data/classes) om het project netjes overzichtelijk te houden. 

Splits vervolgens de huidige code op in files waar de classes/functies horen te staan.

Kijk nog even goed naar de voorbeeldrepo/radio russia demo!

**Comment by sjorra** [comment]
Alles geordend naar het voorbeeld van Radio Russia.

**Comment by sjorra** [comment]
Alles geordend/opgesplitst naar het voorbeeld van Radio Russia.
