### ISSUE TITLE
magic number

### ISSUE THREAD

**Issue by Qvdpost** [pepijnclarijs/rush-hour#11]
Voorkom magic numbers die niet kunnen worden aangepast. Kijk even naar random en het aantal tries die mogen. 100.000. Deze kun je in een functie argument veranderen die je een default value meegeeft van 100.000. Dan hoef je em niet altijd bij het aanroepen van de functie mee te geven, maar kun je em makkelijk later aanpassen in een losse run.

random(arg1, arg2, num_tries=100000)

**Comment by pepijnclarijs** [comment]
Fixed this.
